### ISSUE TITLE
I got 0 ping even in several tests

### ISSUE THREAD

**Issue by rti2** [Surfboardv2ray/batch-fragment-scanner#14]
سلام 
من به جز بار اول که پینگ گرفتم ، کانفیگ های بعدیش همه پینگ 0 میدن 
مخابرات

**Comment by rtmreza** [comment]
سلام مشکل چیه ؟

**Comment by Surfboardv2ray** [comment]
> سلام من به جز بار اول که پینگ گرفتم ، کانفیگ های بعدیش همه پینگ 0 میدن مخابرات

سلام، ممکنه به دلیل عوامل مختلفی باشه، پیشنهاد میکنیم:
* از [آخرین نسخه](https://github.com/Surfboardv2ray/batch-fragment-scanner/releases/download/3.3/batch-fragment-test.ps1) اسکریپت استفاده کنید.
* فایل های pings.txt و xraylogs.txt رو برای سایر مشکلات احتمالی چک کنید.
* از بسته بودن v2rayN و سایر کلاینت های مشابه اطمینان حاصل کنید.
* از سالم بودن کانفیگ خود، از نظر تمیز بودن SNI و آدرس آیپی اطمینان حاصل کنید. پیشنهاد میشه کانفیگ پشت کلادفلیر مانند [ساب ورکرها](https://github.com/vfarid/v2ray-worker) رو تست کنید.
* بعضی از سرویس دهنده‌ها مثل مخابرات، در زمینه کانفیگ های پشت کلادفلیر، در حال حاضر با آیپی تمیز کلادفلیر به خوبی کار میکنند و نیاز به فرگمنت ندارند. به عنوان راهکار جایگزین میتونید از [اسکنر آیپی](https://ircf.space/scanner.php) استفاده کنید.
