### ISSUE TITLE
update

### ISSUE THREAD

**Issue by mehrdadtopme** [Surfboardv2ray/batch-fragment-scanner#15]
Hello
Please update the fragment
New xray core
New Powershell
and new configurations
can support
Thankful

**Comment by Surfboardv2ray** [comment]
> Hello Please update the fragment New xray core New Powershell and new configurations can support Thankful

Hi, link to the latest Xray core and also YouTube instructions were added. Also for the config, it's suggested that you should use a Cloudflare CDN config of your own, or [free ones available](https://github.com/Surfboardv2ray/Proxy-sorter/blob/main/ws_tls/proxies/wstls). Thanks for your considerations and good luck.
