### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by alr86** [Surfboardv2ray/batch-fragment-scanner#2]
لطفا کامند Bash برای لینوکس و اندروید (Termux) هم اضافه کنین

**Comment by Surfboardv2ray** [comment]
> لطفا کامند Bash برای لینوکس و اندروید (Termux) هم اضافه کنین

قطعا کاربردی‌تر خواهد بود، فعلا در حال رفع اشکالات اسکریپت پاورشل هستیم. خیلی ممنون از نظرتون.
