### ISSUE TITLE
Script closes on launch

### ISSUE THREAD

**Issue by armin567ip** [Surfboardv2ray/batch-fragment-scanner#4]

**Comment by leohaghighi** [comment]
i did the folowing and it fixed the issue for me
open terminal or cmd as admin
paste this comand `powershell Set-ExecutionPolicy RemoteSigned`

**Comment by dispel123** [comment]
it didn't fix it for me script closes as soon as it opens

**Comment by arp7vpn** [comment]
same issue : 
the result as below :
PS E:\Fragment Scanner> batch-fragment-test_2.ps1
batch-fragment-test_2.ps1 : The term 'batch-fragment-test_2.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ batch-fragment-test_2.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (batch-fragment-test_2.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command batch-fragment-test_2.ps1 was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\batch-fragment-test_2.ps1". See "get-help about_Command_Precedence" for more details.
PS E:\Fragment Scanner>

**Comment by arp7vpn** [comment]
i found that fix do this steps:
1)open the https://github.com/Surfboardv2ray/batch-fragment-scanner/blob/main/batch-fragment-test.ps1
in chrome or any browser.
2) copy full code
3)make a new file anyname.ps1, the format of the file should be .ps1
4)right click on that file and edit it with any text editor
5)paste code into the file and save it
6)execute the file by right-clicking on it and open with Powershell
enjoy :)

**Comment by Surfboardv2ray** [comment]
> _No description provided._

Are you using Windows 10 or 11?

**Comment by Surfboardv2ray** [comment]
> it didn't fix it for me script closes as soon as it opens

Which version of Windows are you using?

**Comment by aalligithub** [comment]
> it didn't fix it for me script closes as soon as it opens

I had the same issue when I was launching the script in powershell, when I ran the script in VSCode I got an error message "xray.exe not found"

**Comment by Surfboardv2ray** [comment]
> > it didn't fix it for me script closes as soon as it opens
> 
> I had the same issue when I was launching the script in powershell, when I ran the script in VSCode I got an error message "xray.exe not found"

Please try the latest version of the script and let us know if the issue still persists.
