### ISSUE TITLE
ping is always 0 

### ISSUE THREAD

**Issue by leohaghighi** [Surfboardv2ray/batch-fragment-scanner#6]
I couldn't get any results. 
I tried with Irancell, MCI, and Zitel. also used multiple vless ws tls configs. configs do work in v2rayN but when used in the script return 0 ping with the same fragment settings.
i even tried running it while another vpn is connected(Amnezia) and still got 0 ping
![scr](https://github.com/Surfboardv2ray/batch-fragment-scanner/assets/130191092/70abe03b-bc2f-46c2-b269-eb6d948cafac)

**Comment by Surfboardv2ray** [comment]
> I couldn't get any results. I tried with Irancell, MCI, and Zitel. also used multiple vless ws tls configs. configs do work in v2rayN but when used in the script return 0 ping with the same fragment settings. i even tried running it while another vpn is connected(Amnezia) and still got 0 ping ![scr](https://private-user-images.githubusercontent.com/130191092/334168524-70abe03b-bc2f-46c2-b269-eb6d948cafac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzcyMTUsIm5iZiI6MTcxNjgzNjkxNSwicGF0aCI6Ii8xMzAxOTEwOTIvMzM0MTY4NTI0LTcwYWJlMDNiLWJjMmYtNDZjMi1iMjY5LWViNmQ5NDhjYWZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxOTA4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWEyOTdhMmIyYTFmOGQ3MjU5OTQxMTgwMDVmNmE4YjY3Y2Q4MzBiMGRjMDgyOTA5Yzk1NTQwZDhkYjdkZjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xeLCLMF3fPzVXgdt-ExARF_fB2F_EAGJJ0VvxYURGqY)

Thanks for your feedback and thorough explanation. Kindly test this [modified version of the script](https://github.com/Surfboardv2ray/batch-fragment-scanner/releases/download/3.1/batch-fragment-test.ps1) which keeps `xraylogs.txt` for the entire run, and open the logs after the run is completed to check for other problem that might cause the issue.

**Comment by Surfboardv2ray** [comment]
> Same problem here. Running script on window 11 and it returns 0.00 ping for each test

For Windows 11, pleases test [This version](https://github.com/Surfboardv2ray/batch-fragment-scanner/releases/download/3.1/batch-fragment-test.ps1) of the PowerShell script and let us know if the issue is resolved.
