### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by GFW-knocker** [Surfboardv2ray/batch-fragment-scanner#7]
hello dear
please consider these value in search setting:
packets = 1-1
length = 1-3
interval = 5-10

packets =1-1 chunk only first packet which is enough to hide SNI
tlshello mode is a bit different and it seems filtered in some region

another suggestion is to ping multiple time and drop first one because first ping is not accurate 
in fragmentation , first packet chunks intentionally delayed to bypass filtering cause large ping in first attempt
but it doesn't affect subsequent data transfer.

**Comment by Surfboardv2ray** [comment]
> hello dear please consider these value in search setting: packets = 1-1 length = 1-3 interval = 5-10
> 
> packets =1-1 chunk only first packet which is enough to hide SNI tlshello mode is a bit different and it seems filtered in some region
> 
> another suggestion is to ping multiple time and drop first one because first ping is not accurate in fragmentation , first packet chunks intentionally delayed to bypass filtering cause large ping in first attempt but it doesn't affect subsequent data transfer.

Thanks! Will do the first one, it's good to know. Second suggestion will be harder to implement as multiple pings might 
undesirably increase run time on invalid fragments, but I will try
