### ISSUE TITLE
tlshello pocket pings always is 0

### ISSUE THREAD

**Issue by sarahtuska** [Surfboardv2ray/batch-fragment-scanner#8]
hi. thx for great script.

im using both grpc and ws configs. and all of them with tls. but during the test i have ping without tlshello . but with tlshello is bring back ping to always 0. 

is it possible to use other pocket than tlshello on a config using tls? cause in this test those pockts actually i have a good pings . between 300 to 2000.

**Comment by Surfboardv2ray** [comment]
Hello, we removed tlshello thanks to the suggestion from @GFW-knocker #7 so kindly try the latest version of the script [here](https://github.com/Surfboardv2ray/batch-fragment-scanner/releases/download/3.1/batch-fragment-test.ps1), but you can set your desired fragment values by editing the ps1 file under `Arrays of possible values` at any time.
